(() => {
'use strict';
const VERSION='0.1.0';
const state={dataset:null,schema:null,simulation:null};
const $=id=>document.getElementById(id);
const E=Object.fromEntries(['accessBadge','fileInput','fileName','jsonText','exampleBtn','clearBtn','formatBtn','analyzeBtn','analysisMessage','previewSection','datasetTitle','metrics','tablesPreview','simulateBtn','simulationSection','simulationSummary','simulationDetails','warningBox','backupBtn','applyBtn','progressSection','progressText','progressBar','log'].map(id=>[id,$(id)]));
const esc=(v='')=>String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const show=(el,yes=true)=>el&&el.classList.toggle('hidden',!yes);
const txt=v=>v==null?'':String(v).trim();
const normList=v=>Array.isArray(v)&&v[0]==='L'?v.slice(1):(Array.isArray(v)?v:[]);
const eq=(a,b)=>{if(Array.isArray(a)||Array.isArray(b)){const x=normList(a),y=normList(b);return x.length===y.length&&x.every((v,i)=>String(v??'')===String(y[i]??''));}return String(a??'')===String(b??'');};
function notice(m,k=''){E.analysisMessage.className=('notice '+k).trim();E.analysisMessage.textContent=m;show(E.analysisMessage,true);}
function log(m){const d=document.createElement('div');d.textContent=m;E.log.appendChild(d);E.log.scrollTop=E.log.scrollHeight;}
function rows(t){const ids=t.id||[];return ids.map((id,i)=>{const r={id};for(const[k,v]of Object.entries(t))if(k!=='id')r[k]=Array.isArray(v)?v[i]:undefined;return r;});}
function refTarget(type=''){const m=/^(?:Ref|RefList):(.+)$/.exec(type);return m?m[1]:null;}
async function schema(){const ids=await grist.docApi.listTables(),mt=rows(await grist.docApi.fetchTable('_grist_Tables')),mc=rows(await grist.docApi.fetchTable('_grist_Tables_column')),ref=new Map(mt.map(r=>[r.id,r.tableId])),cols=new Map(ids.map(x=>[x,new Map()]));for(const c of mc){const t=ref.get(c.parentId);if(t&&cols.has(t))cols.get(t).set(c.colId,{type:c.type||'Any',formula:Boolean(c.isFormula)});}return{tables:new Set(ids),cols};}
async function tableRows(t){return rows(await grist.docApi.fetchTable(t));}
async function lookup(t,key){const m=new Map();for(const r of await tableRows(t)){const v=r[key];if(v!==null&&v!==undefined&&v!=='')m.set(String(v),r);}return m;}
function parse(){let raw;try{raw=JSON.parse(E.jsonText.value);}catch(e){throw new Error('JSON invalide : '+e.message);}if(!raw||typeof raw!=='object'||Array.isArray(raw))throw new Error('Le JSON racine doit être un objet.');const tables=(raw.tables||[]).map(t=>({table:txt(t.table),key:txt(t.key),mode:txt(t.mode||'upsert').toLowerCase(),rows:Array.isArray(t.rows)?t.rows:[]}));return{name:txt(raw.name)||'Jeu de données',description:txt(raw.description),tables};}
function validate(ds,s){const er=[],warn=[],seen=new Set();if(!ds.tables.length)er.push('Aucune table à traiter.');for(const t of ds.tables){if(!t.table)er.push('Nom de table absent.');if(seen.has(t.table))er.push('Table '+t.table+' déclarée plusieurs fois.');seen.add(t.table);if(!s.tables.has(t.table)){er.push('Table '+t.table+' absente du document.');continue;}const c=s.cols.get(t.table);if(!t.key||!c.has(t.key))er.push(t.table+' : clé métier absente du schéma.');if(c.get(t.key)?.formula)er.push(t.table+'.'+t.key+' est une formule.');if(!['create','update','upsert'].includes(t.mode))er.push(t.table+' : mode invalide.');if(!t.rows.length)warn.push(t.table+' : aucune ligne.');const keys=new Set();t.rows.forEach((r,i)=>{if(!r||typeof r!=='object'||Array.isArray(r)){er.push(t.table+' ligne '+(i+1)+' invalide.');return;}if(!(t.key in r))er.push(t.table+' ligne '+(i+1)+' : clé '+t.key+' absente.');const k=String(r[t.key]??'');if(!k)er.push(t.table+' ligne '+(i+1)+' : clé vide.');if(keys.has(k))er.push(t.table+' : clé '+k+' dupliquée dans le JSON.');keys.add(k);for(const col of Object.keys(r))if(!c.has(col))er.push(t.table+' ligne '+(i+1)+' : colonne '+col+' absente.');});}return{er,warn};}
function planned(t,key,val){const x=state.dataset?.tables.find(a=>a.table===t);return Boolean(x&&x.rows.some(r=>String(r[key]??'')===String(val??'')));}
async function resolveRef(spec,target,cache,allowPlanned){if(spec==null||spec==='')return null;if(typeof spec==='number')return spec;if(!spec||typeof spec!=='object'||!spec.$ref)throw new Error('Référence vers '+target+' : objet $ref attendu.');const r=spec.$ref;if(txt(r.table)!==target)throw new Error('Référence attendue vers '+target+', reçue vers '+txt(r.table)+'.');const ck=target+'::'+txt(r.key);if(!cache.has(ck))cache.set(ck,await lookup(target,txt(r.key)));const hit=cache.get(ck).get(String(r.value));if(hit)return hit.id;if(allowPlanned&&planned(target,txt(r.key),r.value))return '__PLANNED__'+ck+'::'+r.value;throw new Error('Référence introuvable : '+target+'.'+r.key+'='+r.value);}
async function resolve(v,type,cache,allowPlanned){const target=refTarget(type);if(!target)return v;if(type.startsWith('RefList:')){if(v==null||v==='')return['L'];if(Array.isArray(v)&&v.every(x=>typeof x==='number'))return['L',...v];const list=v&&typeof v==='object'&&Array.isArray(v.$refs)?v.$refs:null;if(!list)throw new Error('RefList vers '+target+' : $refs attendu.');const out=[];for(const x of list)out.push(await resolveRef({$ref:x},target,cache,allowPlanned));return['L',...out];}return resolveRef(v,target,cache,allowPlanned);}
function order(ds,s){const names=new Set(ds.tables.map(t=>t.table)),deps=new Map(ds.tables.map(t=>[t.table,new Set()]));for(const t of ds.tables){const c=s.cols.get(t.table);for(const r of t.rows)for(const col of Object.keys(r)){const target=refTarget(c.get(col)?.type||'');if(target&&target!==t.table&&names.has(target))deps.get(t.table).add(target);}}const out=[],vis=new Set(),done=new Set();function go(x){if(done.has(x))return;if(vis.has(x))throw new Error('Dépendance circulaire autour de '+x);vis.add(x);for(const d of deps.get(x)||[])go(d);vis.delete(x);done.add(x);out.push(x);}for(const t of ds.tables)go(t.table);return out;}
function preview(ds,warn){E.datasetTitle.textContent=ds.description?ds.name+' — '+ds.description:ds.name;const n=ds.tables.reduce((a,t)=>a+t.rows.length,0);E.metrics.innerHTML='<div class="metric"><strong>'+ds.tables.length+'</strong>tables</div><div class="metric"><strong>'+n+'</strong>lignes</div><div class="metric"><strong>'+warn.length+'</strong>avertissements</div>';E.tablesPreview.innerHTML=ds.tables.map(t=>'<div class="table-block"><div class="table-title"><strong>'+esc(t.table)+'</strong><span class="pill same">'+esc(t.mode)+'</span></div><div class="table-scroll"><table><thead><tr><th>Clé</th><th>Lignes</th><th>Colonnes JSON</th></tr></thead><tbody><tr><td><code>'+esc(t.key)+'</code></td><td>'+t.rows.length+'</td><td>'+esc([...new Set(t.rows.flatMap(r=>Object.keys(r)))].join(', '))+'</td></tr></tbody></table></div></div>').join('');show(E.previewSection,true);}
async function analyze(){show(E.previewSection,false);show(E.simulationSection,false);show(E.progressSection,false);show(E.analysisMessage,false);try{state.dataset=parse();state.schema=await schema();const v=validate(state.dataset,state.schema);if(v.er.length)throw new Error(v.er.join(' | '));preview(state.dataset,v.warn);notice(v.warn.length?'Modèle valide avec avertissement(s) : '+v.warn.join(' | '):'Jeu de données valide. Vous pouvez lancer la simulation.',v.warn.length?'warning':'success');}catch(e){state.dataset=null;notice('Modèle invalide : '+e.message,'error');}}
async function simulate(){if(!state.dataset)return;E.simulateBtn.disabled=true;try{state.schema=await schema();const ord=order(state.dataset,state.schema),result=[];let creates=0,updates=0,same=0,skips=0,errors=0;for(const id of ord){const t=state.dataset.tables.find(x=>x.table===id),c=state.schema.cols.get(id),cur=await lookup(id,t.key),cache=new Map(),rr=[];for(let i=0;i<t.rows.length;i++){const src=t.rows[i],key=String(src[t.key]),hit=cur.get(key),resolved={},bad=[];for(const[col,val]of Object.entries(src)){try{resolved[col]=await resolve(val,c.get(col)?.type||'Any',cache,true);}catch(e){bad.push(col+': '+e.message);}}if(bad.length){rr.push({i:i+1,key,status:'error',msg:bad.join(' | ')});errors++;continue;}if(!hit){if(t.mode==='update'){rr.push({i:i+1,key,status:'error',msg:'Clé absente en mode update'});errors++;}else{rr.push({i:i+1,key,status:'create',msg:'À créer'});creates++;}continue;}if(t.mode==='create'){rr.push({i:i+1,key,status:'skip',msg:'Existe déjà — ignorée'});skips++;continue;}let n=0;for(const[col,val]of Object.entries(resolved))if(!eq(hit[col],val))n++;if(n){rr.push({i:i+1,key,status:'update',msg:n+' champ(s) à modifier'});updates++;}else{rr.push({i:i+1,key,status:'same',msg:'Déjà conforme'});same++;}}result.push({table:id,key:t.key,rows:rr});}state.simulation={order:ord,result,creates,updates,same,skips,errors};renderSim();}catch(e){notice('Simulation impossible : '+e.message,'error');}finally{E.simulateBtn.disabled=false;}}
function renderSim(){const s=state.simulation;E.simulationSummary.innerHTML='<div class="metric"><strong>'+s.creates+'</strong>à créer</div><div class="metric"><strong>'+s.updates+'</strong>à modifier</div><div class="metric"><strong>'+s.same+'</strong>inchangées</div><div class="metric"><strong>'+s.skips+'</strong>ignorées</div><div class="metric"><strong>'+s.errors+'</strong>erreurs</div>';E.simulationDetails.innerHTML=s.result.map(t=>'<div class="table-block"><div class="table-title"><strong>'+esc(t.table)+'</strong><span>'+t.rows.length+' ligne(s)</span></div><div class="table-scroll"><table><thead><tr><th>#</th><th>'+esc(t.key)+'</th><th>Action</th><th>Détail</th></tr></thead><tbody>'+t.rows.map(r=>'<tr><td>'+r.i+'</td><td><code>'+esc(r.key)+'</code></td><td><span class="pill '+r.status+'">'+r.status+'</span></td><td>'+esc(r.msg)+'</td></tr>').join('')+'</tbody></table></div></div>').join('');E.applyBtn.disabled=s.errors>0||(!s.creates&&!s.updates);E.warningBox.textContent=s.errors?'Des erreurs subsistent. Corrigez le JSON avant application.':(!s.creates&&!s.updates?'Aucune modification à appliquer.':'');show(E.warningBox,Boolean(E.warningBox.textContent));show(E.simulationSection,true);}
function dl(name,obj){const b=new Blob([JSON.stringify(obj,null,2)],{type:'application/json'}),u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),1000);}
async function backup(){if(!state.dataset)return;const out={createdAt:new Date().toISOString(),source:'Grist Data Loader',tables:[]};for(const t of state.dataset.tables)out.tables.push({table:t.table,rows:await tableRows(t.table)});dl('grist-data-backup-'+new Date().toISOString().replace(/[:.]/g,'-')+'.json',out);}
async function apply(){if(!state.simulation||state.simulation.errors)return;E.applyBtn.disabled=true;E.backupBtn.disabled=true;show(E.progressSection,true);E.log.innerHTML='';E.progressBar.style.width='0';try{await backup();log('✓ Sauvegarde téléchargée avant écriture.');let done=0,total=state.simulation.order.length;for(const id of state.simulation.order){state.schema=await schema();const t=state.dataset.tables.find(x=>x.table===id),c=state.schema.cols.get(id),cur=await lookup(id,t.key),cache=new Map(),actions=[];E.progressText.textContent='Application sur '+id+'…';for(const src of t.rows){const key=String(src[t.key]),hit=cur.get(key),resolved={};for(const[col,val]of Object.entries(src))resolved[col]=await resolve(val,c.get(col)?.type||'Any',cache,false);if(!hit){if(t.mode!=='update')actions.push(['AddRecord',id,null,resolved]);continue;}if(t.mode==='create')continue;const ch={};for(const[col,val]of Object.entries(resolved))if(!eq(hit[col],val))ch[col]=val;if(Object.keys(ch).length)actions.push(['UpdateRecord',id,hit.id,ch]);}for(let i=0;i<actions.length;i+=80)await grist.docApi.applyUserActions(actions.slice(i,i+80));log('✓ '+id+' : '+actions.length+' action(s).');done++;E.progressBar.style.width=Math.round(done/Math.max(total,1)*100)+'%';}E.progressText.textContent='Application terminée.';notice('Les données ont été appliquées au document.','success');await simulate();}catch(e){E.progressText.textContent='Application interrompue.';log('ERREUR : '+e.message);notice('Application interrompue : '+e.message,'error');}finally{E.applyBtn.disabled=false;E.backupBtn.disabled=false;}}
E.fileInput.addEventListener('change',async e=>{const f=e.target.files[0];if(!f)return;E.fileName.textContent=f.name;E.jsonText.value=await f.text();});
E.exampleBtn.addEventListener('click',async()=>{try{E.jsonText.value=await(await fetch('example-data.json?v='+VERSION)).text();E.fileName.textContent='example-data.json';}catch(e){notice('Exemple indisponible : '+e.message,'error');}});
E.clearBtn.addEventListener('click',()=>{state.dataset=null;state.simulation=null;E.fileInput.value='';E.fileName.textContent='Aucun fichier chargé';E.jsonText.value='';show(E.previewSection,false);show(E.simulationSection,false);show(E.progressSection,false);show(E.analysisMessage,false);});
E.formatBtn.addEventListener('click',()=>{try{E.jsonText.value=JSON.stringify(JSON.parse(E.jsonText.value),null,2);}catch(e){notice('JSON invalide : '+e.message,'error');}});
E.analyzeBtn.addEventListener('click',analyze);E.simulateBtn.addEventListener('click',simulate);E.backupBtn.addEventListener('click',backup);E.applyBtn.addEventListener('click',apply);
grist.onOptions((_o,i)=>{const full=(i?.accessLevel||i?.access_level)==='full';E.accessBadge.className='status '+(full?'status-ok':'status-wait');E.accessBadge.innerHTML='<span class="dot"></span><span>'+(full?'Accès complet au document':'Accès complet demandé')+'</span>';});
grist.ready({requiredAccess:'full'});
})();